platforms:
  rpipico:
    board: rp2040:rp2040:rpipico
    package: rp2040:rp2040
    gcc:
      features:
      defines:
        - ARDUINO_ARCH_RP2040
      warnings:
      flags:
    lib_deps:
      - libraries/SoftwareSerial
      - libraries/ArduinoJson

packages:
  rp2040:rp2040:
    url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

compile:
  platforms:
    - uno
    lib_deps:
      - libraries/SoftwareSerial
      - libraries/ArduinoJson
#    - m4
#    - esp32
#    - esp8266
#    - rpipico
